[package]
name = "cuda-interposer"
version = "0.2.2"
edition = "2024"
license = "MIT"
description = "A library for writing CUDA driver API hooks in Rust."
repository = "https://github.com/SamKG/cudaflow"

[dependencies]
libc = "0.2.180"
once_cell = "1.21.3"
paste = "1.0.15"
tracing = "0.1.44"
